import { Category } from "@/types";

/**
 * The 12 canonical art traditions and categories of Anjori Arts.
 * Used as a zero-downtime fallback whenever database connectivity,
 * connection pooling, or ISR background revalidation experiences transient delays.
 */
export const DEFAULT_CATEGORIES: Category[] = [
  {
    id: "cat-1",
    slug: "madhubani",
    name: "Madhubani",
    description: "Traditional folk art from the Mithila region known for geometric patterns.",
    cover_image: "/images/categories/madhubani.jpg",
    alt_text: "Handcrafted authentic Madhubani painting depicting traditional peacocks, fish, and Tree of Life with natural mineral dyes",
    display_order: 10,
  },
  {
    id: "cat-2",
    slug: "tanjore",
    name: "Tanjore",
    description: "Classical South Indian art famous for rich colours and gold foil embellishments.",
    cover_image: "/images/categories/tanjore.jpg",
    alt_text: "Classical Tanjore gold foil relief painting of Lord Krishna with rich 22-karat gold leaf and gemstone embellishments",
    display_order: 20,
  },
  {
    id: "cat-3",
    slug: "warli",
    name: "Warli Art",
    description: "Tribal art style from Maharashtra depicting daily life and nature.",
    cover_image: "/images/categories/warli.jpg",
    alt_text: "Traditional Warli tribal painting on red-ochre clay surface depicting the circular Tarpa harvest dance in rice pigment",
    display_order: 30,
  },
  {
    id: "cat-4",
    slug: "mythological-devotional",
    name: "Mythological & Devotional",
    description: "Intricate devotional paintings capturing stories of the divine.",
    cover_image: "/images/categories/mythological-devotional.jpg",
    alt_text: "Original monochrome charcoal and acrylic painting of Lord Ganesha on deep black canvas by Anjori Arts",
    display_order: 40,
  },
  {
    id: "cat-12",
    slug: "mandala",
    name: "Mandala Art",
    description: "Intricate geometric designs that represent the universe, offering visual harmony and meditative focus.",
    cover_image: "/images/categories/mandala.jpg",
    alt_text: "Original radiant lotus deity mandala painting with jewel-toned cerulean blue and gold petals by Anjori Arts",
    display_order: 50,
  },
  {
    id: "cat-5",
    slug: "contemporary",
    name: "Contemporary Works",
    description: "Modern artistic expressions breaking traditional boundaries.",
    cover_image: "/images/categories/contemporary.jpg",
    alt_text: "Contemporary Indian fine art gallery painting with expressive impasto palette knife textures and gold leaf accents",
    display_order: 60,
  },
  {
    id: "cat-6",
    slug: "portraiture",
    name: "Portraiture",
    description: "Lifelike custom portraits tailored to capture the essence of the subject.",
    cover_image: "/images/categories/portraiture.jpg",
    alt_text: "Bespoke fine art oil painting portrait of an Indian woman with classical chiaroscuro candlelight illumination",
    display_order: 70,
  },
  {
    id: "cat-7",
    slug: "figurative",
    name: "Figurative Painting",
    description: "Artworks retaining strong references to the real world and human form.",
    cover_image: "/images/categories/figurative.jpg",
    alt_text: "Original narrative figurative painting celebrating the Chipko Movement and rural Indian heritage by Anjori Arts",
    display_order: 80,
  },
  {
    id: "cat-8",
    slug: "customised-branding",
    name: "Branding & Logo Art",
    description: "Art-based conceptual branding, logos, and business artwork.",
    cover_image: "/images/categories/customised-branding.jpg",
    alt_text: "Bespoke artisanal branding identity mockup with metallic gold lotus emblem, calligraphy pen, and custom wax seal",
    display_order: 90,
  },
  {
    id: "cat-9",
    slug: "poster-designing",
    name: "Poster Designing",
    description: "Aesthetic and communicative poster designs.",
    cover_image: "/images/categories/poster-designing.jpg",
    alt_text: "Vintage Indian art exhibition poster design with intricate block-print ornamental borders and classical typography",
    display_order: 100,
  },
  {
    id: "cat-10",
    slug: "cyanotype",
    name: "Cyanotype Prints",
    description: "Photographic printing process that produces a cyan-blue print.",
    cover_image: "/images/categories/cyanotype.jpg",
    alt_text: "Botanical Prussian blue cyanotype sun-print of wild ferns and wildflowers on deckled-edge cotton rag paper",
    display_order: 110,
  },
  {
    id: "cat-11",
    slug: "earrings",
    name: "Handcrafted Earrings",
    description: "Unique artisan-made earrings combining traditional motifs with modern wearability.",
    cover_image: "/images/categories/earrings.jpg",
    alt_text: "Handcrafted artisan terracotta clay jhumka earrings with traditional Indian hand-painted motifs on cream linen",
    display_order: 120,
  },
];

